#!/bin/bash
cp /opt/midi-router-client-cli/share/applications/midi-router-client-cli.desktop /usr/share/applications/midi-router-client-cli.desktop
cp /opt/midi-router-client-cli/share/icons/hicolor/256x256/apps/midi-router-client-cli.png /usr/share/icons/hicolor/256x256/apps/midi-router-client-cli.png
chmod 777 /opt/midi-router-client-cli/bin/midi-router-client-cli.sh
